/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stu;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Gourav Chandra Upadhayay
 */
public class EditStud extends javax.swing.JFrame implements ActionListener {

    private Connection con;

    /**
     * Creates new form EditStud
     */
    public EditStud() {
        initComponents();
        setIcon();
        setTitle("Search Student");
        con = Connect.getConnection();
        srch.addActionListener(this);
        bck.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        srch = new javax.swing.JButton();
        bck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Student Record");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Enrollment No.");

        srch.setText("Search");

        bck.setText("Back");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(srch)
                .addGap(51, 51, 51)
                .addComponent(bck)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srch)
                    .addComponent(bck))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton srch;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        String st = txt.getText();
        Boolean flag = true;
        if (ae.getActionCommand() == "Search") {
            try {
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery("select * from record where enrollment='" + st + "'");
                if (rs.next()) {
                    AddStud ads = new AddStud();
                    ads.enroll.setText(rs.getString(1));

                    String name = rs.getString(2);
                    String[] name1 = name.split(" ");
                    ads.fnme.setText(name1[0]);
                    ads.lnme.setText(name1[1]);

                    ads.dtechoser.setDate(new SimpleDateFormat("dd/mm/yyyy").parse(rs.getString(3)));

                    String gender = rs.getString(4);
                    if (gender.equals("Male")) {
                        ads.jRadioButton1.setSelected(true);
                        ads.jRadioButton2.setSelected(false);
                    } else {
                        ads.jRadioButton1.setSelected(false);
                        ads.jRadioButton2.setSelected(true);
                    }

                    ads.cat.setSelectedItem(rs.getString(5));
                    ads.progrm.setSelectedItem(rs.getString(6));

                    String sbat = rs.getString(7);
                    String[] sbat1 = sbat.split("-");
                    ads.bat1.setSelectedItem(sbat1[0]);
                    ads.bat2.setSelectedItem(sbat1[1]);

                    String addr = rs.getString(8);
                    String[] addr1 = addr.split(",");
                    ads.add1.setText(addr1[0]);
                    ads.add2.setText(addr1[1]);
                    ads.stat.setSelectedItem(addr1[2]);
                    ads.pin.setText(addr1[3]);

                    ads.phn.setText(rs.getString(9));
                    ads.eid.setText(rs.getString(10));
                    ads.mnme.setText(rs.getString(11));
                    ads.fanme.setText(rs.getString(12));
                    ads.gua.setText(rs.getString(13));
                    ads.occup.setText(rs.getString(14));
                    ads.pphn.setText(rs.getString(15));
                    ads.peid.setText(rs.getString(16));

                    ads.setVisible(true);
                    setVisible(false);
                } else if (flag) {
                    JOptionPane.showMessageDialog(this, "Please Enter Enrollment No.", "Error", JOptionPane.WARNING_MESSAGE);
                    txt.setText("");
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            } catch (ParseException ex) {
                Logger.getLogger(EditStud.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            MainPage mp = new MainPage();
            mp.setVisible(true);
            setVisible(false);
        }
    }
    private void setIcon() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icon.jpg")));

    }
}
